runtime: php55
api_version: 1
threadsafe: true

handlers:
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /static
  static_dir: static

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: index.php
  secure: always

# [START env_vars]
env_variables:
  GCS_BUCKET_NAME: "benyamin-biz.appspot.com"
  MYSQL_DSN: mysql:unix_socket=/cloudsql/tln-construction:asia-east1:tln-construction;dbname=benyamin
  MYSQL_USER: benyamin
  MYSQL_PASSWORD: 'Ad3!N'
# [END env_vars]

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
